### ISSUE TITLE
sQTL data still available?

### ISSUE THREAD

**Issue by nmra-cwilks** [stephenslab/susie-paper#10]
Hi,

We're starting to work on the sQTL example from the paper as a ramp-up to using our own data with susieR, using the helpful walkthrough here:
https://stephenslab.github.io/susie-paper/manuscript_results/Li_2016_splice_QTL.html

However, I'm getting a timeout when accessing http://eqtl.uchicago.edu/jointLCL/

Are the sQTL example data available somewhere else?

Thanks,
Chris

**Comment by gaow** [comment]
@btrx-cwilks Unfortunately, we don't maintain the website. But Yang Li on the Li 2016 paper is a UChicago faculty. He might know what's going on with that website. 

However, if your goal is to prepare yourself with running it on your own data, perphaps reading this workflow documentation you'll have some idea of input format, and therefore can possibly analyze your data directly if you follow these formatting requirements?

https://github.com/stephenslab/susie-paper/blob/master/src/20180704_MolecularQTL_Workflow.ipynb

**Comment by nmra-cwilks** [comment]
thanks for the quick response!
I think we can make do w/o the sample data.
