### ISSUE TITLE
Which part of the repo is where you generate simulated datasets before making comparison with other methods?

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susie-paper#12]
Which part of the repo is where you generate simulated datasets before making comparison with other methods?

**Comment by gaow** [comment]
We use [DSC](https://stephenslab.github.io/dsc-wiki/overview)  to perform the benchmark including data generation and performance comparison, see more at https://stephenslab.github.io/susie-paper/finemapping_benchmark.html
