### ISSUE TITLE
Where can I find the comparison with hierinf? 

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susie-paper#13]
Where can I find the comparison with hierinf? The paper says hierinf uses assumed hierarchy but didn't specify which hierarchy is used. I'm looking for this information as well.

**Comment by gaow** [comment]
@garyzhubc this repo links to another benchmark repo which we later extended also for SuSiE RSS (Zou et al 2022) paper. https://github.com/stephenslab/dsc-finemap  you can find hierinf related benchmark here.
