### ISSUE TITLE
Windows(PowerShell) friendly docker commands?

### ISSUE THREAD

**Issue by ZacZZZ** [stephenslab/susie-paper#4]
Dear Stephens Lab,

I have Docker Desktop installed. 
I tried to run the alias section on 
https://stephenslab.github.io/susie-paper/index.html
`alias susie-docker='docker run --security-opt label:disable -t --rm '\
'-P -h SuSiE -w $PWD -v $HOME:/home/$USER -v /tmp:/tmp -v $PWD:$PWD '\
'-u $UID:${GROUPS[0]} -e HOME=/home/$USER -e USER=$USER susie/susie-paper'`
through PowerShell.

But it returned error

> -P : The term '-P' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + -P -h SuSiE -w $($PWD) -v $($HOME):/home/$($USER) -v /tmp:/tmp -v $($ ...
> + ~~
>     + CategoryInfo          : ObjectNotFound: (-P:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

I did search seems doskey can do the job of alias but I haven't found an easy way to implement it.
Any suggestions will be appreciated!

**Comment by ZacZZZ** [comment]
Updating my question... I don't know why it sent out automatically...

**Comment by gaow** [comment]
@ZacZZZ I dont have the knowledge (or even a Windows machine) to test it out, but obviously `alias` is not something you might use on Windows. 

The docker command itself is:

```
docker run --security-opt label:disable -t --rm -P -h SuSiE -w $PWD -v $HOME:/home/$USER -v /tmp:/tmp -v $PWD:$PWD -u $UID:${GROUPS[0]} -e HOME=/home/$USER -e USER=$USER susie/susie-paper
```

and it works on Linux and Mac. Maybe you want to give it a go for Windows? that is instead of setting `alias` and typing in `susie-docker` you type in this entire command

**Comment by ZacZZZ** [comment]
The one you suggested gives the error 

```
At line:1 char:72
+ ... urity-opt label:disable -t --rm -P -h SuSiE -w $PWD -v $HOME:/home/$U ...
+                                                            ~~~~~~
Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to
delimit the name.
At line:1 char:106
```

I modified it to 
`docker run --security-opt label:disable -t --rm -P -h SuSiE -w $($PWD) -v $($HOME):/home/$($USER) -v /tmp:/tmp -v $($PWD):$($PWD) -u $($UID):${GROUPS[0]} -e HOME=/home/$($USER) -e USER=$($USER) susie/susie-paper uname -sn`

and it returns 
```
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: invalid reference format.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```
