### ISSUE TITLE
Large prior variance estimate

### ISSUE THREAD

**Issue by adrtin** [stephenslab/susie-paper#9]
I tried SuSiE using summary statistics on a high LD region. SuSiE converged. However, the estimated prior variance using the optimal method was huge: 3269017.
The results included 5 credible sets with 1 variant each. However, these 5 variants were in high LD with each other.
My understanding is: variants in different credible sets should be relatively independent.
This kind of results did not happen with other regions. 
I can send the R object that contains the SuSiE results.
Please advise, thank you

**Comment by stephens999** [comment]
the high estimated prior variance almost certainly indicates an inconsistency/mismatch between the LD reference and the LD in the study sample. See https://www.biorxiv.org/content/10.1101/2021.11.03.467167v1 for discussion of the importance of a good match, and possible diagnostics.

Bottom line is I would not trust the results; the way to improve would be
to get a better LD reference. (Or are using an in-sample LD matrix?)

**Comment by adrtin** [comment]
Thank you for response.
The LD matrix was generated using the same sample that generated the summary statistics.
I saw similar issues in the susieR github page.
Best regards,

**Comment by gaow** [comment]
@adrtin did you use R or R^2? LD in our case should be R not R^2. Another quick check is to use `susieR::get_cs_correlation` to evaluate the correlation between your 5 CSs. I've seen cases where you see the correlation of two CSs is -1 while the z-scores are identical -- that indicates you have a flip in the allele coding between your summary stats results and your LD matrix.

**Comment by stephens999** [comment]
yes, this is unexpected if the LD matrix was (correctly) generated using the same sample that generated the summary statistics. Something is probably wrong.

**Comment by adrtin** [comment]
@gaow, thank you for the response.
I used R generated from plink. In the genotype file, not all minor alleles are A1 as assumed by plink.
Now I added --keep-allele-order in the plink command for generate the LD, the results look more reasonable.
The responses from you and @stephens999 have been very helpful. I'll close the issue. Thank you.
